healthy_article_1_健康.csv
healthy_article_2_飲食.csv
healthy_article_3_瘦身.csv
healthy_article_4_運動.csv
healthy_article_5_美麗.csv
healthy_article_6_護口腔.csv
healthy_article_7_足健康.csv
healthy_article_8_健康百科.csv

In [1]:
# 讀取train資料
# import pandas as pd
# df_health = pd.read_csv("healthy_article_1_健康.csv", encoding="utf-8")
# df_diet = pd.read_csv("healthy_article_2_飲食.csv", encoding="utf-8")
# df_slim = pd.read_csv("healthy_article_3_瘦身.csv", encoding="utf-8")
# df_sport = pd.read_csv("healthy_article_4_運動.csv", encoding="utf-8")
# df_beautiful = pd.read_csv("healthy_article_5_美麗.csv", encoding="utf-8")
# df_oralcare = pd.read_csv("healthy_article_6_護口腔.csv", encoding="utf-8")
# df_foothealth = pd.read_csv("healthy_article_7_足健康.csv", encoding="utf-8")
# df_encyclopedia = pd.read_csv("healthy_article_8_健康百科.csv", encoding="utf-8")

In [2]:
# 去除重複文章
# df_health = df_health.drop_duplicates("URL")
# df_diet = df_diet.drop_duplicates("URL")
# df_slim = df_slim.drop_duplicates("URL")
# df_sport = df_sport.drop_duplicates("URL")
# df_beautiful = df_beautiful.drop_duplicates("URL")
# df_oralcare = df_oralcare.drop_duplicates("URL")
# df_foothealth = df_foothealth.drop_duplicates("URL")
# df_encyclopedia = df_encyclopedia.drop_duplicates("URL")

In [3]:
# 去除重複後存檔，下次可直接讀
# df_health.to_csv("df_health.csv", encoding="utf-8")
# df_diet.to_csv("df_diet.csv", encoding="utf-8")
# df_slim.to_csv("df_slim.csv", encoding="utf-8")
# df_sport.to_csv("df_sport.csv", encoding="utf-8")
# df_beautiful.to_csv("df_beautiful.csv", encoding="utf-8")
# df_oralcare.to_csv("df_oralcare.csv", encoding="utf-8")
# df_foothealth.to_csv("df_foothealth.csv", encoding="utf-8")
# df_encyclopedia.to_csv("df_encyclopedia.csv", encoding="utf-8")

In [4]:
import pandas as pd
df_health = pd.read_csv("df_health.csv", encoding="utf-8")
df_diet = pd.read_csv("df_diet.csv", encoding="utf-8")
df_slim = pd.read_csv("df_slim.csv", encoding="utf-8")
df_sport = pd.read_csv("df_sport.csv", encoding="utf-8")
df_beautiful = pd.read_csv("df_beautiful.csv", encoding="utf-8")
df_oralcare = pd.read_csv("df_oralcare.csv", encoding="utf-8")
df_foothealth = pd.read_csv("df_foothealth.csv", encoding="utf-8")
df_encyclopedia = pd.read_csv("df_encyclopedia.csv", encoding="utf-8")

In [5]:
# 貼標
healthy_list = [df_health, df_diet, df_slim, df_sport, df_beautiful, df_oralcare, df_foothealth, df_encyclopedia]
k = 0
for df in healthy_list:
    df["target"] = str(k)
    k += 1

In [6]:
# 合併已貼標的DataFrame
train_df = pd.concat(healthy_list, axis=0, ignore_index=True)
train_df = train_df.drop("Unnamed: 0", axis=1)
train_df

title  \
0      吃對食物，儲備抗癌電力！養生專家陳月卿：大腸癌讓她重獲新生   
1      揮別空巢期宅男，施昇輝：50後，比理財更重要的是為自己而活   
2             灰指甲好不了？容易被誤認為灰指甲的6種皮膚病   
3      三高世代，慢性病是必然？蔬果多酚降風險，看懂哪些食物適合你   
4         血型與罹癌風險有關？研究：2種血型容易得胃癌、胰臟癌   
...                              ...   
11479          心絞痛是心肌梗塞前兆！心絞痛的8個危險警訊   
11480     雞肉：肉類中的紓壓天王！放鬆助眠、直腸癌風險降50％   
11481      茄子：抗氧化力強，防細胞受傷！想選新鮮貨注意1重點   
11482      堅果維生素C是蘋果17倍！吃堅果防癌抗發炎秘訣公開   
11483         白髮變黑：讓頭皮血液動起來！1招按摩隨時養髮   

                                                    URL Published date  \
0      https://www.everydayhealth.com.tw//article/22370     2019-08-12   
1      https://www.everydayhealth.com.tw//article/22380     2019-08-12   
2      https://www.everydayhealth.com.tw//article/22366     2019-08-12   
3      https://www.everydayhealth.com.tw//article/22269     2019-08-12   
4      https://www.everydayhealth.com.tw//article/22350     2019-08-12   
...                                                 ...            ...   
11479  https://www.everydayhealth.com.tw//article/18394     2019-06-04   
11480  https://www.everydayhealth.com.tw//article/16603     2018-09-14   
11481  https://www.everydayhealth.com.tw//article/16604     2018-08-11   
11482  https://www.everydayhealth.com.tw//article/16605     2018-10-18   
11483  https://www.everydayhealth.com.tw//article/16350     2018-03-31   

                                                 content target  
0      【早安健康／陳月卿（癌症關懷基金會董事長）】\n健康見證人：精力湯讓我降低化療痛苦、走過大腸...      0  
1      【早安健康／施昇輝（理財作家、樂活大叔）】\n離開職場，最怕成宅男\n\n二○一六年十月一日...      0  
2      【早安健康／游懿聖（懿聖皮膚科院長）】\n真的是灰指甲嗎？\n\n灰指甲就是黴菌感染到指甲，...      0  
3      【早安健康／張承宇報導】不少研究都指出，蔬菜水果中豐富的多酚具備抗氧化、預防疾病的效果，是需...      0  
4      【早安健康／王彥文報導】日本人喜歡用血型來統計性格，但近兩年歐美連續幾項調查時期超過三十年的...      0  
...                                                  ...    ...  
11479  【早安健康／蘇柏儒報導】心絞痛又被稱為狹心症，是源自於心臟缺氧所引發的胸部疼痛，最常見的原因...      7  
11480  【早安健康編輯部】雞肉是肉類裡面脂肪含量最低的，特別是雞胸肉部分。雞胸肉每100g之中含有2...      7  
11481  【早安健康編輯部】茄子是夏季盛產的蔬菜，紫色的外皮富含抗氧化能力超群的花青素，但許多人卻不愛...      7  
11482  【早安健康編輯部／綜合報導】今天吃堅果了嗎？眾所周知，堅果是健康食品，一直以來，堅果就是休閒...      7  
11483  【早安健康／林明慧報導】還記得發現第一根白髮長出來時的反應嗎？雖說白髮是「智慧的象徵」，但現...      7  

[11484 rows x 5 columns]

In [7]:
# jieba 切割
# 將文章斷字
from jieba.analyse import extract_tags
from jieba import cut, set_dictionary, load_userdict, lcut
import os
import re


if not os.path.exists("dict.txt.big"):
    print("幫你下載大辭典")
    url = "https://github.com/fxsjy/jieba/raw/master/extra_dict/dict.txt.big"
    urlretrieve(url,"dict.txt.big")
else:
    print("你已經下載過了")

set_dictionary("dict.txt.big")

stopwords = [line.strip() for line in open("stopword.txt", 'r', encoding='utf-8').readlines()] 

def stopword(cutted_list) -> list:
    stop_list = []
    for i in cutted_list:
        if i not in stopwords:
            stop_list.append(i)
    return stop_list

def jieba_tokenize(text) -> list:
    text = re.sub("[\s+\.\!\/_,$%^*(+\"\']+|[+——！，。？、~@#￥%……&*（）【／】]+", "",text)  # 取代所有標點
    return lcut(text) 

train_df["cut_stop_list"] = train_df["content"].apply(jieba_tokenize).apply(stopword)

train_df["cut_stop_str"] = pd.Series(" ".join(i) for i in train_df["cut_stop_list"])

Building prefix dict from C:\Users\Big data\Desktop\與個人電腦同步\dict.txt.big ...
Loading model from cache C:\Users\BIGDAT~1\AppData\Local\Temp\jieba.ucb71b8d63cf48e6767cb5787264d5a3b.cache


你已經下載過了


Loading model cost 1.120 seconds.
Prefix dict has been built succesfully.


In [8]:
# 建立Sequential 神經網路: embedding, flatten, relu, dropout, softmax
from keras.models import Sequential
from keras.layers import Embedding
from keras.layers import Dense, Flatten, Dropout
model = Sequential()
model.add(Embedding(2000, 32, input_length=100))
model.add(Flatten())
model.add(Dense(256, activation="relu"))
model.add(Dropout(0.25))
model.add(Dense(8, activation="softmax"))
model.summary()

Using TensorFlow backend.
c:\users\big data\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\big data\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\big data\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16",

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 100, 32)           64000     
_________________________________________________________________
flatten_1 (Flatten)          (None, 3200)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               819456    
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 2056      
Total params: 885,512
Trainable params: 885,512
Non-trainable params: 0
_________________________________________________________________


In [9]:
# 資料預處理 提取前精華的兩千字，每個字給予一個數字當代表
from keras.preprocessing.text import Tokenizer
tok = Tokenizer(num_words=2000)
tok.fit_on_texts(train_df["cut_stop_str"])
print(tok.word_index)

{'會': 1, '健康': 2, '中': 3, '吃': 4, '身體': 5, '時': 6, '更': 7, '運動': 8, '食物': 9, '日本': 10, '肌肉': 11, '效果': 12, '做': 13, '改善': 14, '早安': 15, '預防': 16, '症狀': 17, '攝取': 18, '研究': 19, '維生素': 20, '飲食': 21, '導致': 22, '醫師': 23, '建議': 24, '增加': 25, '疾病': 26, '脂肪': 27, '高': 28, '含有': 29, '指出': 30, '患者': 31, '時間': 32, '減少': 33, '體內': 34, '治療': 35, '降低': 36, '裡': 37, '營養': 38, '發現': 39, '分鐘': 40, '動作': 41, '影響': 42, '女性': 43, '血管': 44, '一個': 45, '提高': 46, '疼痛': 47, '喝': 48, '方法': 49, '10': 50, '原因': 51, '人體': 52, '血液': 53, '前': 54, '睡眠': 55, '食用': 56, '纖維': 57, '壓力': 58, '功能': 59, '代謝': 60, '生活': 61, '透過': 62, '糖尿病': 63, '作用': 64, '方式': 65, '簡單': 66, '神經': 67, '細胞': 68, '食材': 69, '約': 70, '太': 71, '血液循環': 72, '蔬菜': 73, '蛋白質': 74, '皮膚': 75, '刺激': 76, '一頁': 77, '按摩': 78, '說': 79, '腸道': 80, '歲': 81, '即可': 82, '伸展': 83, '發生': 84, '姿勢': 85, '放鬆': 86, '疲勞': 87, '呼吸': 88, '發炎': 89, '想': 90, '消除': 91, '選擇': 92, '先': 93, '一種': 94, '習慣': 95, '膽固醇': 96, '水': 97, '特別': 98, '補充': 99, '變得': 100, '膝蓋': 101, '狀態': 1

In [10]:
# 根據 "精華兩千字" 將每篇文章序列化
train_df_seq = tok.texts_to_sequences(train_df["cut_stop_str"])
# test_df_seq = tok.texts_to_sequences(test_df["article"])
pd.DataFrame(train_df_seq)

0     1     2     3     4     5     6     7     8     9     ...  1417  \
0        15     2   291   103  1804     2   955    36  1981   695  ...   NaN   
1        15     2  1554  1784   629   673   412   673   588   187  ...   NaN   
2        15     2  1776   346   444   716   220   798   798   446  ...   NaN   
3        15     2   428   677   193   542    19    30     3   783  ...   NaN   
4        15     2   193    10   292   981  1121   545  1298   187  ...   NaN   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
11479    15     2   193   567   126  1986   197   969    47   195  ...   NaN   
11480    15     2   705  1205   561    27   120    98  1770  1099  ...   NaN   
11481    15     2   705  1870  1177    73   106   160   204  1415  ...   NaN   
11482    15     2   705   917   193     4   284   284     2   151  ...   NaN   
11483    15     2  1392   193   555    39  1321   223  1919   360  ...   NaN   

       1418  1419  1420  1421  1422  1423  1424  1425  1426  
0       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
1       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...  
11479   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
11480   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
11481   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
11482   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
11483   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[11484 rows x 1427 columns]

In [11]:
# 公平起見，每篇文章提取最後100個關鍵詞，截長補短(補 0)
from keras.preprocessing.sequence import pad_sequences
train_df_pad = pad_sequences(train_df_seq, maxlen=100)
# test_df_pad = pad_sequences(test_df_seq, maxlen=100)
pd.DataFrame(train_df_pad)

In [12]:
# 編譯model，此處應選擇 categorical_crossentropy

model.compile(loss="categorical_crossentropy",
              optimizer="adam",
              metrics=["accuracy"])

In [20]:
# 對 y 做 One-Hot encoding
from keras.utils.np_utils import to_categorical
y_train_cat = to_categorical(train_df["target"])
print(y_train_cat)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [21]:
# 開始跑 MLP模型
model.fit(train_df_pad, y_train_cat,
          batch_size=200, epochs=10,
          validation_split=0.1, verbose=2)

Train on 10335 samples, validate on 1149 samples
Epoch 1/10
 - 1s - loss: 0.2094 - acc: 0.9420 - val_loss: 11.9519 - val_acc: 0.0522
Epoch 2/10
 - 1s - loss: 0.0690 - acc: 0.9934 - val_loss: 12.7520 - val_acc: 0.0487
Epoch 3/10
 - 1s - loss: 0.0236 - acc: 0.9983 - val_loss: 13.1249 - val_acc: 0.0487
Epoch 4/10
 - 1s - loss: 0.0128 - acc: 0.9990 - val_loss: 13.3610 - val_acc: 0.0496
Epoch 5/10
 - 1s - loss: 0.0122 - acc: 0.9987 - val_loss: 13.5224 - val_acc: 0.0444
Epoch 6/10
 - 1s - loss: 0.0093 - acc: 0.9989 - val_loss: 13.4850 - val_acc: 0.0505
Epoch 7/10
 - 1s - loss: 0.0072 - acc: 0.9990 - val_loss: 13.6665 - val_acc: 0.0453
Epoch 8/10
 - 1s - loss: 0.0083 - acc: 0.9989 - val_loss: 13.6167 - val_acc: 0.0496
Epoch 9/10
 - 1s - loss: 0.0073 - acc: 0.9990 - val_loss: 13.7471 - val_acc: 0.0453
Epoch 10/10
 - 1s - loss: 0.0069 - acc: 0.9988 - val_loss: 13.7083 - val_acc: 0.0496


In [ ]:
# 評估模型 (若有做 train test split 的話)

# model.evaluate(test_df_pad, test_df["target"])

In [ ]:
######

In [22]:
# 可以透過此功能觀看每一層輸出，此處觀察embedding層在做甚麼
from keras.models import Model
partial = Model(inputs=model.input, outputs=model.layers[0].output)
partial.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1_input (InputLaye (None, 100)               0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 100, 32)           64000     
Total params: 64,000
Trainable params: 64,000
Non-trainable params: 0
_________________________________________________________________


In [24]:
# 觀察結果: 詞語被分成32維度向量了
reverse_dict = {tok.word_index[k]:k for k in tok.word_index}
print("Embedding前:", reverse_dict[test_df_pad[0][-1]])
print("Embedding後:", partial.predict(test_df_pad)[0][-1])

KeyError: -1

In [25]:
# 製作新model
from keras.models import Sequential
from keras.layers import Embedding, SimpleRNN
from keras.layers import Dense, Flatten, Dropout
model = Sequential()
model.add(Embedding(2000, 32, input_length=100))
model.add(SimpleRNN(16))
model.add(Dense(256, activation="relu"))
model.add(Dropout(0.25))
model.add(Dense(8, activation="softmax"))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 100, 32)           64000     
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 16)                784       
_________________________________________________________________
dense_3 (Dense)              (None, 256)               4352      
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 2056      
Total params: 71,192
Trainable params: 71,192
Non-trainable params: 0
_________________________________________________________________


In [26]:
# 編譯

model.compile(loss="categorical_crossentropy",
              optimizer="adam",
              metrics=["accuracy"])

In [28]:
# 跑 model
model.fit(train_df_pad, y_train_cat,
          batch_size=200, epochs=3,
          validation_split=0.1, verbose=2)

Train on 10335 samples, validate on 1149 samples
Epoch 1/3
 - 1s - loss: 0.7008 - acc: 0.7025 - val_loss: 7.8376 - val_acc: 0.0313
Epoch 2/3
 - 1s - loss: 0.6158 - acc: 0.7358 - val_loss: 8.3103 - val_acc: 0.0044
Epoch 3/3
 - 1s - loss: 0.5540 - acc: 0.7730 - val_loss: 8.5876 - val_acc: 0.0383


In [29]:
# 評估
model.evaluate(train_df_pad, y_train_cat)

11484/11484 [==============================] - 1s 103us/step


[1.28410317848178, 0.738679902473006]